FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /build

COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done
RUN dotnet restore

COPY . ./

RUN dotnet publish GraphifyCode.MCP/GraphifyCode.MCP.csproj -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /build/out .

ENV ASPNETCORE_URLS=http://+:5000

EXPOSE 5000

ENTRYPOINT ["dotnet", "GraphifyCode.MCP.dll"]
